-- Create master_data_dev table with the same structure as master_data_sept_2
CREATE TABLE IF NOT EXISTS master_data_dev (
  id                    SERIAL PRIMARY KEY,
  new_field             TEXT,
  service_category      TEXT,
  service_sub_category  TEXT,
  state_id_pk           TEXT,
  state_name            TEXT,
  state_code            TEXT,
  filename              TEXT,
  page_number           TEXT,
  service_id_pk         TEXT,
  service_code          TEXT,
  service_description   TEXT,
  rate                  TEXT,
  rate_last_updated     TEXT,
  rate_effective_date   DATE,
  duration_unit         TEXT,
  minutes               TEXT,
  program               TEXT,
  modifier_1            TEXT,
  modifier_1_details    TEXT,
  modifier_2            TEXT,
  modifier_2_details    TEXT,
  modifier_3            TEXT,
  modifier_3_details    TEXT,
  modifier_4            TEXT,
  modifier_4_details    TEXT,
  fee                   TEXT,
  max_fee               TEXT,
  modifier_id_pk        TEXT,
  service_id_fk         TEXT,
  prior_auth_required   TEXT,
  comments              TEXT,
  location_region       TEXT,
  update_id_pk          TEXT,
  times_rate_updated    TEXT,
  percentage_change     TEXT,
  last_database_refresh TEXT,
  requires_pa           TEXT,
  rate_per_hour         TEXT,
  provider_type         TEXT,
  age                   TEXT,
  unnamed_40            TEXT,
  unnamed_41            TEXT,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW(),
  updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW()
);

-- Create master_data_prod table with the same structure as master_data_sept_2
CREATE TABLE IF NOT EXISTS master_data_prod (
  id                    SERIAL PRIMARY KEY,
  new_field             TEXT,
  service_category      TEXT,
  service_sub_category  TEXT,
  state_id_pk           TEXT,
  state_name            TEXT,
  state_code            TEXT,
  filename              TEXT,
  page_number           TEXT,
  service_id_pk         TEXT,
  service_code          TEXT,
  service_description   TEXT,
  rate                  TEXT,
  rate_last_updated     TEXT,
  rate_effective_date   DATE,
  duration_unit         TEXT,
  minutes               TEXT,
  program               TEXT,
  modifier_1            TEXT,
  modifier_1_details    TEXT,
  modifier_2            TEXT,
  modifier_2_details    TEXT,
  modifier_3            TEXT,
  modifier_3_details    TEXT,
  modifier_4            TEXT,
  modifier_4_details    TEXT,
  fee                   TEXT,
  max_fee               TEXT,
  modifier_id_pk        TEXT,
  service_id_fk         TEXT,
  prior_auth_required   TEXT,
  comments              TEXT,
  location_region       TEXT,
  update_id_pk          TEXT,
  times_rate_updated    TEXT,
  percentage_change     TEXT,
  last_database_refresh TEXT,
  requires_pa           TEXT,
  rate_per_hour         TEXT,
  provider_type         TEXT,
  age                   TEXT,
  unnamed_40            TEXT,
  unnamed_41            TEXT,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW(),
  updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Create indexes on commonly queried columns (same as master_data_sept_2 if they exist)
-- Uncomment and adjust if needed:
-- CREATE INDEX IF NOT EXISTS idx_master_data_dev_state_code ON master_data_dev(state_code);
-- CREATE INDEX IF NOT EXISTS idx_master_data_dev_service_code ON master_data_dev(service_code);
-- CREATE INDEX IF NOT EXISTS idx_master_data_prod_state_code ON master_data_prod(state_code);
-- CREATE INDEX IF NOT EXISTS idx_master_data_prod_service_code ON master_data_prod(service_code);

